influxdb:
  image: januswel/influxdb
  container_name: influxdb
  volumes:
    - ${PWD}/influxdb.conf:/etc/influxdb/influxdb.conf
    - /var/lib/influxdb/data
  ports:
    - 8083:8083
    - 8086:8086
    - 8088:8088
  restart: always
